version: '3.0'
#@see: https://code-maze.com/docker-hub-vs-creating-docker-registry/

services:
    my-regestry:
        image: registry:latest
        container_name: my-registry
        volumes:
            - registry:/var/lib/registry
        ports:
            - "50000:5000"
        restart: unless-stopped
volumes:
    registry:
