version: '3.0'

services:
  my-registry:
          image: couchbase:community-5.1.1
    container_name: jobleads-crawler-couchbase-master
    volumes:
        - "couchbase_master:/opt/couchbase/var"
    ports:
        - "8091:8091"   #8091: Couchbase Web console, REST/HTTP interface
        - "8092:8092"   #8092: Views, queries, XDCR
        - "8093:8093"   #8093: Query services (4.0+)
        - "8094:8094"   #8094: Full-text Search (4.5+)
        - "8095:8095"   #8095: Analytics (5.5+)
        - "8096:8096"   #8096: Eventing (5.5+)
        - "11207:11207" # 11207: Smart client library data node access (SSL)
        - "11210:11210" # 11210: Smart client library/moxi data node access
        - "11211:11211" # 11211: Legacy non-smart client library data node access
        - "18091:18091" # 18091: Couchbase Web console, REST/HTTP interface (SSL)
        - "18092:18092" # 18092: Views, query, XDCR (SSL)
        - "18093:18093" # 18093: Query services (SSL) (4.0+)
        - "18094:18094" # 18094: Full-text Search (SSL) (4.5+)
        - "18095:18095" # 18095: Analytics (SSL) (5.5+)
        - "18096:18096" # 18096: Eventing (SSL) (5.5+)
    restart: unless-stopped
volumes:
  couchbase_master:
