-- 
-- @see
--  https://www.percona.com/blog/2018/02/05/four-ways-to-execute-mysql-group-by/
--  https://www.percona.com/blog/2018/01/29/using-generated-columns-in-mysql-5-7-to-increase-query-performance/
-- 
